# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_camera(object):
    def setupUi(self, camera):
        camera.setObjectName("camera")
        camera.resize(524, 354)
        self.groupBox = QtWidgets.QGroupBox(camera)
        self.groupBox.setGeometry(QtCore.QRect(40, 240, 441, 91))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnTake = QtWidgets.QPushButton(self.groupBox)
        self.btnTake.setObjectName("btnTake")
        self.horizontalLayout.addWidget(self.btnTake)
        self.btnRedo = QtWidgets.QPushButton(self.groupBox)
        self.btnRedo.setObjectName("btnRedo")
        self.horizontalLayout.addWidget(self.btnRedo)
        self.btnYes = QtWidgets.QPushButton(self.groupBox)
        self.btnYes.setObjectName("btnYes")
        self.horizontalLayout.addWidget(self.btnYes)
        self.btnCancel = QtWidgets.QPushButton(self.groupBox)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.groupBox_2 = QtWidgets.QGroupBox(camera)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 20, 451, 201))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")

        self.retranslateUi(camera)
        QtCore.QMetaObject.connectSlotsByName(camera)

    def retranslateUi(self, camera):
        _translate = QtCore.QCoreApplication.translate
        camera.setWindowTitle(_translate("camera", "Form"))
        self.btnTake.setText(_translate("camera", "拍照"))
        self.btnRedo.setText(_translate("camera", "重拍"))
        self.btnYes.setText(_translate("camera", "确定"))
        self.btnCancel.setText(_translate("camera", "取消"))
